package ru.geekbrains.paymentservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2020-04-14T16:41:34.555+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.geekbrains.ru/PaymentService", name = "PaymentPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PaymentPort {

    @WebMethod
    @WebResult(name = "getProductResponse", targetNamespace = "http://www.geekbrains.ru/PaymentService", partName = "getProductResponse")
    public GetProductResponse getProduct(
        @WebParam(partName = "getProductRequest", name = "getProductRequest", targetNamespace = "http://www.geekbrains.ru/PaymentService")
        GetProductRequest getProductRequest
    );

    @WebMethod
    @WebResult(name = "getPaymentResponse", targetNamespace = "http://www.geekbrains.ru/PaymentService", partName = "getPaymentResponse")
    public GetPaymentResponse getPayment(
        @WebParam(partName = "getPaymentRequest", name = "getPaymentRequest", targetNamespace = "http://www.geekbrains.ru/PaymentService")
        GetPaymentRequest getPaymentRequest
    );
}
